PersonelFollow.WebUI/Components/NavbarViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using PersonelFollow.WebUI.Services.Session;

namespace PersonelFollow.WebUI.Components
{
    public class NavbarViewComponent : ViewComponent
    {
        private readonly ISessionService _sessionService;

        public NavbarViewComponent(ISessionService sessionService)
        {
            _sessionService = sessionService;
        }

        public IViewComponentResult Invoke()
        {
            ViewBag.GirisVarMi = _sessionService.GetSessionUserInformation() != null;
            ViewBag.UserName = _sessionService.GetSessionUserInformation();
            return View("Default");
        }
    }
}

PersonelFollow.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PersonelFollow.WebUI</title>
    <link href="~/bower_components/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    @await Component.InvokeAsync("Navbar")
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <div class="row pt-3">
            @RenderBody()
        </div>
    </div>


    <script src="~/bower_components/jquery/dist/jquery.min.js"></script>
    <script src="~/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="~/bower_components/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/bower_components/jquery-validation-unobtrusive/src/jquery.validate.unobtrusive.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>